### ISSUE TITLE
Problems installing coconut on python 3.7

### ISSUE THREAD

**Issue by hoishing** [evhub/coconut#476]
When installing coconut in python 3.7 using pip:

`pip install coconut[all]` 

cPyparsing is failed to build, it doesn't support python 3.7 yet...

I then tried to install coconut using conda. Installation succeeded, but couldn't launch jupyter console using 

`coconut --jupyter console` 

Error message as follow:

`ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts'`

After some Googling I found that the jupyter console didn't support prompt_toolkit 2.0 yet, see:

[https://github.com/ipython/ipython/issues/11261](https://github.com/ipython/ipython/issues/11261)

and it could be solved by downgrading prompt_toolkit.

`conda install prompt_toolkit=1.0.15`

Everything is fine afterwards.

**Comment by hoishing** [comment]
As cPyparsing couldn't build in python 3.7, I also tried to install coconut in python 3.6, starting with pip: 

`pip install coconut[all] `

It completed with version conflict between ipython and prompt_toolkit. Error message:

`ipython 5.4.1 has requirement prompt-toolkit<2.0.0,>=1.0.4, but you'll have prompt-toolkit 2.0.7 which is incompatible.`

The result is jupyter console failed to run. I end up fixing it by upgrading ipython:

`pip install --upgrade ipython`

**Comment by hoishing** [comment]
What about installing coconut with conda in python 3.6? I got the following error while launching jupyter console:

`pkg_resources.VersionConflict: (pyparsing 2.3.0 (.../lib/python3.6/site-packages), Requirement.parse('pyparsing<2.2.1,>=2.2.0'))`

I then downgrade pyparsing to 2.2.0 with:

`conda install pyparsing=2.2.0`

and everything works again.

**Comment by hoishing** [comment]
In short, if I don't use cPyparsing, installing everything using conda in python 3.7 then downgrade prompt_toolkit to 1.0.15 will be the easiest approach. 

Otherwise using pip to install coconut[all] in python 3.6, then upgrade ipython can get the job done.

Struggled quite some time on these dependency problems... hope it can help other new comers.

**Comment by evhub** [comment]
For the cPyparsing issue, see https://github.com/evhub/cpyparsing/issues/1.

**Comment by evhub** [comment]
@hoishing I think all of these issues have been resolved in the latest version.
